### ISSUE TITLE
Fails to build from a directory with a long name

### ISSUE THREAD

**Issue by jbeich** [OpenVisualCloud/SVT-AV1#1227]
Regressed by 2a3babcdc0d9
```
$ git clone https://github.com/OpenVisualCloud/SVT-AV1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ cd aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$ cmake -G Ninja
[...]
Source/Lib/Encoder/Globals/EbEncHandle.c:16:10: fatal error: 'EbVersion.h' file not found
#include "EbVersion.h"
         ^~~~~~~~~~~~~
1 error generated.
```

**Comment by jbeich** [comment]
Nevermind. I can't reproduce in jail.

**Comment by ePirat** [comment]
This was an issue due to incorrect dependency declarations in CMake, causing random failures depending when a specific target would be built. This was fixed with #1229.
